"use strict";
let varrible1 = "true";
let varrible2 = "false";
let varrible3 = 17;
let varrible4 = undefined;
let varrible5 = null;
console.log(typeof varrible1);
console.log(typeof varrible2);
console.log(typeof varrible3);
console.log(typeof varrible4);
console.log(typeof varrible5);